default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" }  %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "djo" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "cicibu" } %>

development:
  <<: *default
  database: RealtimeSearchAnalytics_development

test:
  <<: *default
  database: RealtimeSearchAnalytics_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>